### ISSUE TITLE
Rust Graphics Meetup 3 CFP

### ISSUE THREAD

**Issue by AngelOnFira** [gfx-rs/meetup#3]
## Rust Graphics Meetup

The third Rust Graphics Meetup will take place on the [28th of January 2023 at 16:00 GMT](https://everytimezone.com/s/feafb968)! This meetup is a platform for formal talks about projects in the Rust graphics ecosystem. This meetup will be run by @kvark, @cwfitzgerald, and @AngelOnFira.

## Call for Presentations

We're looking for speakers, so if you have something you'd like to show off, or give a talk about, comment on this issue with the template below:

```
Name:
Talk title:
Talk description:
Contact email:
Estimated duration: (10/30)
```

You can watch the recordings from the last meetup here:
- [Vismut](https://www.youtube.com/watch?v=0IsllXP7_pY)
- [Screen-13](https://www.youtube.com/watch?v=ywZznsCXUjs)
- [WGPU](https://www.youtube.com/watch?v=DDG4bcGs7zM)

## Streaming Logistics

We use [StreamYard](https://streamyard.com) to host the meetup. Using it is quite similar to another browser video chat tool, like Google Meet. We'll do a tech test before the meetup, so you can become familiar with how it is used.

**Comment by kvark** [comment]
Name: Dzmitry
Talk title: Hello, Blade!
Talk description: Introducing a lean and mean graphics library 'Blade', for fun and no profit.
Contact email: kvark at fastmail
Estimated duration: 30

**Comment by John-Nagle** [comment]
Name: John Nagle
Talk title: A metaverse client in Rust / Rend3 / WGPU
Talk description: How to deal with excessively complex content and still get good frame rates.
Contact email: nagle@animats.com
Estimated duration:  20

How does this work? Open Broadcaster?

**Comment by AngelOnFira** [comment]
> How does this work? Open Broadcaster?

@John-Nagle good question! I'll add a section to the original message that gives more details :100:

**Comment by aclysma** [comment]
I pre-recorded a presentation that's ~13 minutes long called "Implementing an Extensible Renderer." Assuming it's not too late to get it queued up for this meetup, I can be around in discord to answer questions. I just don't want to have to speak or hassle with technology issues at 8 AM in the morning :D  (I'll DM the link to download it to @AngelOnFira and @kvark on discord)

Name: aclysma
Talk title: Implementing an Extensible Renderer
Talk description: Quick introduction to Rafx, and some ideas for making more extensible renderers
Contact email: aclysma at gmail
Estimated duration: 15

**Comment by cwfitzgerald** [comment]
Name: Connor Fitzgerald
Talk title: `Rend3: High Performance, Cross Platform, GPU Driven Rendering in wgpu and WebGPU`
Talk description: An overview of the current state of rend3: new data and gpu driven rendering model, performance improvements, and a look into the future.
Contact email: connorwadefitzgerald aat gmail
Estimated Duration: 30

**Comment by AngelOnFira** [comment]
## Schedule

Here's the draft schedule for next week's meetup. Let me know if there are any issues with your timeslot!

- (16:00 - 16:05) Introductions 👋 - @kvark & @cwfitzgerald 
- (16:05 - 16:40) Hello, Blade! - @kvark
- (16:40 - 16:55) Implementing an Extensible Renderer - @aclysma
- (16:55 - 17:25) Rend3: High Performance, Cross Platform, GPU Driven Rendering in wgpu and WebGPU - @cwfitzgerald 
- (17:25 - 17:30) Conclusion - @kvark & @cwfitzgerald

**Comment by John-Nagle** [comment]
I'm going to cancel. Next time I can probably do a live demo, but I am not ready yet.

**Comment by cwfitzgerald** [comment]
Sorry to hear that, but excited to see what you do with even more time 😄

**Comment by John-Nagle** [comment]
I know. I'm stuck down in the plumbing of talking to the Second Life/Open Simulator server right now. The user presses up arrow, and a lot has to happen before your avatar moves and the camera adjusts to match. It's just grunt work, and reverse engineering the half-documented interface.

**Comment by cwfitzgerald** [comment]
Ah sounds delightful.

Edited the schedule accordingly.

**Comment by AngelOnFira** [comment]
~~@kvark @aclysma @cwfitzgerald could I get a description for each of your talks? I'll try to make an announcement post tomorrow :)~~

Edit: Totally forgot that I already have that 😅

**Comment by AngelOnFira** [comment]
Thanks for the talks everyone! I'll try getting to posting the individual videos soon, but I'll close this issue. See y'all next time!
